//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_AuthenticationTable
    {
        public int AuthenticationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Institutions { get; set; }
        public string Specialty { get; set; }
        public string EducationalBackground { get; set; }
        public Nullable<System.DateTime> EnrolTime { get; set; }
        public Nullable<System.DateTime> GraduationTime { get; set; }
        public byte[] Diploma { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string ReviewRemarks { get; set; }
        public Nullable<System.DateTime> Checktime { get; set; }
    }
}
