//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_CreditorAttornTable
    {
        public int CreditorAttornID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TenderTitle { get; set; }
        public string Rate { get; set; }
        public Nullable<decimal> WaitPeriods { get; set; }
        public Nullable<decimal> AttornPeriods { get; set; }
        public Nullable<decimal> AllPeriods { get; set; }
        public Nullable<decimal> WaitCapital { get; set; }
        public Nullable<decimal> WaitAccrual { get; set; }
        public Nullable<decimal> AttornPrice { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<int> PurchaserUserID { get; set; }
        public Nullable<System.DateTime> PurchaseTime { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
