//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ExpensestypeTable
    {
        public int ExpensestypeID { get; set; }
        public string ExpensestypeName { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> FundStatusID { get; set; }
        public Nullable<int> LoanexpensesTypeID { get; set; }
        public string bucklemoney { get; set; }
    }
}
