//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_limitrecordTable
    {
        public int limitrecordID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LimitTypeID { get; set; }
        public Nullable<int> limitkindID { get; set; }
        public Nullable<int> limitoperateID { get; set; }
        public Nullable<decimal> Summoney { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
