//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ModuleTable
    {
        public int ModuleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string identificationName { get; set; }
        public string Byname { get; set; }
        public string Name { get; set; }
        public string Edition { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Describe { get; set; }
        public Nullable<int> ModuleStatusID { get; set; }
    }
}
