//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_NoticeTable
    {
        public int NoticeID { get; set; }
        public string Title { get; set; }
        public string NoticeContent { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> NoticeTypeID { get; set; }
        public Nullable<int> NoticeStatusID { get; set; }
        public Nullable<System.DateTime> IssueTime { get; set; }
        public string ArticleLabel { get; set; }
    }
}
