//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_UserLoginDetailTable
    {
        public int UserLoginDetailID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string PostBox { get; set; }
        public Nullable<decimal> LoginFrequency { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public Nullable<System.DateTime> lastLoginTime { get; set; }
        public string lastLoginIP { get; set; }
        public Nullable<System.DateTime> EndLoginTime { get; set; }
        public string EndLogin { get; set; }
    }
}
