//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_WebLiuYan
    {
        public int WebliuyanID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<System.DateTime> LiuYanTime { get; set; }
        public string Callnumber { get; set; }
        public string QQ { get; set; }
        public string MailBox { get; set; }
        public string Content { get; set; }
    }
}
