//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DYXTEntities : DbContext
    {
        public DYXTEntities()
            : base("name=DYXTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_AccountTable> B_AccountTable { get; set; }
        public virtual DbSet<B_AuthenticationTable> B_AuthenticationTable { get; set; }
        public virtual DbSet<B_CapitalrecordTable> B_CapitalrecordTable { get; set; }
        public virtual DbSet<B_CostTypeTable> B_CostTypeTable { get; set; }
        public virtual DbSet<B_CreditorAttornTable> B_CreditorAttornTable { get; set; }
        public virtual DbSet<B_Deductexpenses> B_Deductexpenses { get; set; }
        public virtual DbSet<B_ExchangeTreetopLoan> B_ExchangeTreetopLoan { get; set; }
        public virtual DbSet<B_ExpensestypeTable> B_ExpensestypeTable { get; set; }
        public virtual DbSet<B_FollowTable> B_FollowTable { get; set; }
        public virtual DbSet<B_InvestTable> B_InvestTable { get; set; }
        public virtual DbSet<B_Jurisdictio> B_Jurisdictio { get; set; }
        public virtual DbSet<B_LimitApplicationTable> B_LimitApplicationTable { get; set; }
        public virtual DbSet<B_limitrecordTable> B_limitrecordTable { get; set; }
        public virtual DbSet<B_LoanDetailTable> B_LoanDetailTable { get; set; }
        public virtual DbSet<B_MaterialAttestationTable> B_MaterialAttestationTable { get; set; }
        public virtual DbSet<B_ModuleTable> B_ModuleTable { get; set; }
        public virtual DbSet<B_NoticeTable> B_NoticeTable { get; set; }
        public virtual DbSet<B_NoticeTypeTable> B_NoticeTypeTable { get; set; }
        public virtual DbSet<B_OfflineRechargeTable> B_OfflineRechargeTable { get; set; }
        public virtual DbSet<B_OverdueLoanTable> B_OverdueLoanTable { get; set; }
        public virtual DbSet<B_PersonalSpreadMessage> B_PersonalSpreadMessage { get; set; }
        public virtual DbSet<B_phoneauthenticationTable> B_phoneauthenticationTable { get; set; }
        public virtual DbSet<B_SentTable> B_SentTable { get; set; }
        public virtual DbSet<B_SpreadRecordTable> B_SpreadRecordTable { get; set; }
        public virtual DbSet<B_SpreadTypeTable> B_SpreadTypeTable { get; set; }
        public virtual DbSet<B_SpreadUserTable> B_SpreadUserTable { get; set; }
        public virtual DbSet<B_UserCashRecordTable> B_UserCashRecordTable { get; set; }
        public virtual DbSet<B_UserExpensesTable> B_UserExpensesTable { get; set; }
        public virtual DbSet<B_UserlimitTable> B_UserlimitTable { get; set; }
        public virtual DbSet<B_UserRechargeRecordTable> B_UserRechargeRecordTable { get; set; }
        public virtual DbSet<B_UserTable> B_UserTable { get; set; }
        public virtual DbSet<B_VideoauthenticationTable> B_VideoauthenticationTable { get; set; }
        public virtual DbSet<B_VIPUserTable> B_VIPUserTable { get; set; }
        public virtual DbSet<B_WebsiteExpensesTable> B_WebsiteExpensesTable { get; set; }
        public virtual DbSet<B_WebsiteReceivableDetail> B_WebsiteReceivableDetail { get; set; }
        public virtual DbSet<S_ExamineTable> S_ExamineTable { get; set; }
        public virtual DbSet<S_FundCostTable> S_FundCostTable { get; set; }
        public virtual DbSet<S_FundStatustable> S_FundStatustable { get; set; }
        public virtual DbSet<S_ItemTypeTable> S_ItemTypeTable { get; set; }
        public virtual DbSet<S_limitkindTable> S_limitkindTable { get; set; }
        public virtual DbSet<S_limitoperateTable> S_limitoperateTable { get; set; }
        public virtual DbSet<S_LimitTypeTable> S_LimitTypeTable { get; set; }
        public virtual DbSet<S_LoanDeadlineTable> S_LoanDeadlineTable { get; set; }
        public virtual DbSet<S_LoanexpensesType> S_LoanexpensesType { get; set; }
        public virtual DbSet<S_ModularDetailITable> S_ModularDetailITable { get; set; }
        public virtual DbSet<S_ModuleStatusTable> S_ModuleStatusTable { get; set; }
        public virtual DbSet<S_NoticeStatusTable> S_NoticeStatusTable { get; set; }
        public virtual DbSet<S_OperateTypeTable> S_OperateTypeTable { get; set; }
        public virtual DbSet<S_OpTypeTable> S_OpTypeTable { get; set; }
        public virtual DbSet<S_PayTypeTable> S_PayTypeTable { get; set; }
        public virtual DbSet<S_RechargeTypeTable> S_RechargeTypeTable { get; set; }
        public virtual DbSet<S_RepaymentWayTable> S_RepaymentWayTable { get; set; }
        public virtual DbSet<S_SendstatusTable> S_SendstatusTable { get; set; }
        public virtual DbSet<S_StatusTable> S_StatusTable { get; set; }
        public virtual DbSet<S_Transmitstatus> S_Transmitstatus { get; set; }
        public virtual DbSet<S_Treetoptypetalbe> S_Treetoptypetalbe { get; set; }
        public virtual DbSet<S_UserTypeTable> S_UserTypeTable { get; set; }
        public virtual DbSet<T_City> T_City { get; set; }
        public virtual DbSet<T_District> T_District { get; set; }
        public virtual DbSet<T_Province> T_Province { get; set; }
        public virtual DbSet<B_ManagerRecord> B_ManagerRecord { get; set; }
        public virtual DbSet<B_WebLiuYan> B_WebLiuYan { get; set; }
        public virtual DbSet<B_UserLoginDetailTable> B_UserLoginDetailTable { get; set; }
        public virtual DbSet<B_LoanTable> B_LoanTable { get; set; }
    }
}
