//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYXTHT_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Treetoptypetalbe
    {
        public int TreetoptypeID { get; set; }
        public string Treetoptype { get; set; }
        public string TreetopName { get; set; }
        public string Identifier { get; set; }
        public string Describe { get; set; }
        public Nullable<int> FundStatusID { get; set; }
        public Nullable<int> LimitTypeID { get; set; }
        public Nullable<int> LoanDeadlineID { get; set; }
        public Nullable<decimal> YearRate { get; set; }
        public string ExamineTime { get; set; }
        public string LowestTenderMoney { get; set; }
        public string HighestTenderMoney { get; set; }
        public string Overduefatalism { get; set; }
        public string FreezeBail { get; set; }
    }
}
