//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_ExchangeTreetopLoan
    {
        public int ExchangeTreetopID { get; set; }
        public string PaymentNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Loantitle { get; set; }
        public Nullable<decimal> ExchangeMoney { get; set; }
        public string Rate { get; set; }
        public Nullable<decimal> EArrearagePrincipal { get; set; }
        public Nullable<decimal> ERepayPrincipal { get; set; }
        public Nullable<decimal> EAlreadyPrincipal { get; set; }
        public Nullable<decimal> EPayableInterest { get; set; }
        public Nullable<int> RepaymentWayID { get; set; }
        public Nullable<int> LoanDeadlineID { get; set; }
        public string LeastUnit { get; set; }
        public string AllExchangePortion { get; set; }
        public string stopExchangePortion { get; set; }
        public string WaitExchangePortion { get; set; }
        public string AlreadyBuyBackPortion { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string ExamineRemarks { get; set; }
    }
}
