//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_InvestTable
    {
        public int InvestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> ReceivablePrincipal { get; set; }
        public Nullable<decimal> InvestMoney { get; set; }
        public Nullable<decimal> ReceivableInterest { get; set; }
        public Nullable<decimal> CountermandPrincipal { get; set; }
        public Nullable<decimal> NotRetrievePrincipal { get; set; }
        public Nullable<System.DateTime> InvestTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> WhetherAttorn { get; set; }
        public string InvestReason { get; set; }
        public string LoanTreetop { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<int> ExchangeTreetopID { get; set; }
    }
}
