//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_MaterialAttestationTable
    {
        public int MaterialAttestationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public byte[] Picture { get; set; }
        public string Integral { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Remarks { get; set; }
        public string ReviewRemarks { get; set; }
    }
}
