//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_OverdueLoanTable
    {
        public int OverdueLoanID { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<System.DateTime> PayableTime { get; set; }
        public Nullable<decimal> PayablePrincipal { get; set; }
        public Nullable<int> OverdueDay { get; set; }
        public Nullable<int> WebsiteWhetherPayStatusID { get; set; }
        public Nullable<decimal> WebsiteWhetherPaymoney { get; set; }
        public Nullable<System.DateTime> WebsiteWhetherPayTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> RealityRepaymentTime { get; set; }
    }
}
