//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_UserlimitTable
    {
        public int UserlimitID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Creditlimetl { get; set; }
        public Nullable<decimal> Cavailable { get; set; }
        public Nullable<decimal> Cfreeze { get; set; }
        public Nullable<decimal> Warrantlimetl { get; set; }
        public Nullable<decimal> Wavailable { get; set; }
        public Nullable<decimal> Wfreeze { get; set; }
        public Nullable<decimal> Mortgagelimitli { get; set; }
        public Nullable<decimal> Mavailable { get; set; }
        public Nullable<decimal> Mfreeze { get; set; }
        public Nullable<decimal> Roamlitil { get; set; }
        public Nullable<decimal> Ravailable { get; set; }
        public Nullable<decimal> Rfreeze { get; set; }
    }
}
