//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_UserTable
    {
        public int UserID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string UserName { get; set; }
        public string PostBox { get; set; }
        public string PayPassword { get; set; }
        public string TrueName { get; set; }
        public string IDCardNo { get; set; }
        public string PhoneNumber { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BornDate { get; set; }
        public string NativePlace { get; set; }
        public string MarriageState { get; set; }
        public string Issue { get; set; }
        public string EducationalBackground { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public string MonthIncome { get; set; }
        public string SocialSecurity { get; set; }
        public string housingCondition { get; set; }
        public string WhetherBuyCar { get; set; }
        public Nullable<decimal> PropertyAmounts { get; set; }
        public Nullable<decimal> UsableMoney { get; set; }
        public Nullable<decimal> FreezeMoney { get; set; }
        public Nullable<decimal> WaitMoney { get; set; }
        public Nullable<decimal> CompensatoryMoney { get; set; }
        public Nullable<int> PayTypeID { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Subbranch { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string ExamineRemarks { get; set; }
        public Nullable<decimal> Integral { get; set; }
    }
}
