//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_UserRechargeRecordTable
    {
        public int RechargeRecordID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RechargeTypeID { get; set; }
        public Nullable<int> PayTypeID { get; set; }
        public string TradeNumber { get; set; }
        public Nullable<decimal> RechargeMoney { get; set; }
        public string RechargePoundage { get; set; }
        public Nullable<decimal> RealityAccountMoney { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string ExamineRemarks { get; set; }
        public string operateIP { get; set; }
    }
}
