//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_VIPUserTable
    {
        public int VIPUserID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string VipDeadline { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> WhetherPayment { get; set; }
        public string ExamineRemarks { get; set; }
        public Nullable<System.DateTime> ExamineTime { get; set; }
    }
}
