//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiYouQianTaiXiTong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_RepaymentWayTable
    {
        public int RepaymentWayID { get; set; }
        public string IdentificationName { get; set; }
        public string RepaymentWayName { get; set; }
        public string Title { get; set; }
        public Nullable<int> FundStatusID { get; set; }
        public string AlgorithmMessage { get; set; }
    }
}
